### ISSUE TITLE
Ошибка при запуске на Mac OS

### ISSUE THREAD

**Issue by Prestapro** [sergo-code/hh-ru-auto-resume-raising#1]
Когда пытаюсь запустить команду: python3 bot.py
Получаю этот баг

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 692, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1021, in _new_conn
    conn = self.ConnectionCls(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 311, in __init__
    HTTPConnection.__init__(self, host, port, strict=strict, timeout=timeout, **kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 130, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 859, in __init__
    self._validate_host(self.host)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1238, in _validate_host
    raise InvalidURL(f"URL can't contain control characters. {host!r} "
http.client.InvalidURL: URL can't contain control characters. 'none or http' (found at least ' ')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 692, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1021, in _new_conn
    conn = self.ConnectionCls(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 311, in __init__
    HTTPConnection.__init__(self, host, port, strict=strict, timeout=timeout, **kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 130, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 859, in __init__
    self._validate_host(self.host)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1238, in _validate_host
    raise InvalidURL(f"URL can't contain control characters. {host!r} "
urllib3.exceptions.ProtocolError: ('Connection aborted.', InvalidURL("URL can't contain control characters. 'none or http' (found at least ' ')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/uiteam/Sites/localhost/hh.ru/bot.py", line 21, in <module>
    if is_valid(proxy) or proxy == 'None':
  File "/Users/uiteam/Sites/localhost/hh.ru/services/check_proxy.py", line 7, in is_valid
    requests.head(url, proxies={'https': proxy})
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', InvalidURL("URL can't contain control characters. 'none or http' (found at least ' ')"))
```

**Comment by sergo-code** [comment]
Это ошибка в конфиге, в поле прокси вы должны оставить либо None либо данные для подключения к прокси (добавлю это в README).
Пример:
proxy=None
или
proxy=http://login:password@ip:port

**Comment by sergo-code** [comment]
Это ошибка в конфиге, в поле прокси вы должны оставить либо None либо данные для подключения к прокси (добавлю это в README).
Пример:
proxy=None
или
proxy=http://login:password@ip:port/

> Когда пытаюсь запустить команду: python3 bot.py Получаю этот баг
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 692, in urlopen
>     conn = self._get_conn(timeout=pool_timeout)
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
>     return conn or self._new_conn()
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1021, in _new_conn
>     conn = self.ConnectionCls(
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 311, in __init__
>     HTTPConnection.__init__(self, host, port, strict=strict, timeout=timeout, **kw)
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 130, in __init__
>     _HTTPConnection.__init__(self, *args, **kw)
>   File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 859, in __init__
>     self._validate_host(self.host)
>   File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1238, in _validate_host
>     raise InvalidURL(f"URL can't contain control characters. {host!r} "
> http.client.InvalidURL: URL can't contain control characters. 'none or http' (found at least ' ')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
>     resp = conn.urlopen(
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
>     retries = retries.increment(
>   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 692, in urlopen
>     conn = self._get_conn(timeout=pool_timeout)
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
>     return conn or self._new_conn()
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1021, in _new_conn
>     conn = self.ConnectionCls(
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 311, in __init__
>     HTTPConnection.__init__(self, host, port, strict=strict, timeout=timeout, **kw)
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 130, in __init__
>     _HTTPConnection.__init__(self, *args, **kw)
>   File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 859, in __init__
>     self._validate_host(self.host)
>   File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1238, in _validate_host
>     raise InvalidURL(f"URL can't contain control characters. {host!r} "
> urllib3.exceptions.ProtocolError: ('Connection aborted.', InvalidURL("URL can't contain control characters. 'none or http' (found at least ' ')"))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/uiteam/Sites/localhost/hh.ru/bot.py", line 21, in <module>
>     if is_valid(proxy) or proxy == 'None':
>   File "/Users/uiteam/Sites/localhost/hh.ru/services/check_proxy.py", line 7, in is_valid
>     requests.head(url, proxies={'https': proxy})
>   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 100, in head
>     return request("head", url, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 547, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', InvalidURL("URL can't contain control characters. 'none or http' (found at least ' ')"))
> ```

**Comment by RootShell-coder** [comment]
`URL can't contain control characters. 'none or http' (found at least ' ')`
proxy=None or http://login:password@ip:port
your rename and edit .env_pub file?
