### ISSUE TITLE
is broken - fake_useragent.errors (HTTP Error 503: Service Unavailable)

### ISSUE THREAD

**Issue by RootShell-coder** [sergo-code/hh-ru-auto-resume-raising#3]
Hi
I am getting this error  `fake_useragent.errors`

```  
 | Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
   | Traceback (most recent call last):
   |   File "/home/hh/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 154, in load
   |     for item in get_browsers(verify_ssl=verify_ssl):
   |   File "/home/hh/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 99, in get_browsers
   |     html = html.split('<table class="w3-table-all notranslate">')[1]
   | IndexError: list index out of range
   | Traceback (most recent call last):
   |   File "/home/hh/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 154, in load
   |     for item in get_browsers(verify_ssl=verify_ssl):
   |   File "/home/hh/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 99, in get_browsers
   |     html = html.split('<table class="w3-table-all notranslate">')[1]
   | IndexError: list index out of range
   | 
   | During handling of the above exception, another exception occurred:
   | 
   | Traceback (most recent call last):
   |   File "/home/hh/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 64, in get
   |     with contextlib.closing(urlopen(
   |   File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
   |     return opener.open(url, data, timeout)
   |   File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
   |     response = meth(req, response)
   |   File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
   |     response = self.parent.error(
   |   File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
   |     return self._call_chain(*args)
   |   File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
   |     result = func(*args)
   |   File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
   |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
   | urllib.error.HTTPError: HTTP Error 503: Service Unavailable
   | 
   | During handling of the above exception, another exception occurred:
   | 
   | Traceback (most recent call last):
   |   File "/home/hh/bot.py", line 3, in <module>
   |     from handlers import (register_handler_base,
   |   File "/home/hh/handlers/__init__.py", line 1, in <module>
   |     from .base import register_handler_base
   |   File "/home/hh/handlers/base.py", line 4, in <module>
   |     from services import is_admin
   |   File "/home/hh/services/__init__.py", line 1, in <module>
   |     from .auto_raise_resume import tasks
   |   File "/home/hh/services/auto_raise_resume.py", line 6, in <module>
   |     from .connecting import obj, bot
   |   File "/home/hh/services/connecting.py", line 11, in <module>
   |     obj = HHru(Config.phone, Config.password, Config.proxy)
   |   File "/home/hh/services/main.py", line 17, in __init__
   |     self.user_agent = UserAgent().chrome
   |   File "/home/hh/.local/lib/python3.10/site-packages/fake_useragent/fake.py", line 69, in __init__
   |     self.load()
   |   File "/home/hh/.local/lib/python3.10/site-packages/fake_useragent/fake.py", line 75, in load
   |     self.data = load_cached(
   |   File "/home/hh/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 250, in load_cached
   |     update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
   |   File "/home/hh/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 245, in update
   |     write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
   |   File "/home/hh/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 187, in load
   |     ret = json.loads(get(
   |   File "/home/hh/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 84, in get
   |     raise FakeUserAgentError('Maximum amount of retries reached')
   | fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
^C
```

**Comment by sergo-code** [comment]
https://github.com/fake-useragent/fake-useragent/issues/157
